Frontend/Pedalea.WebApp/Pedalea.WebApp/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Mvc;
using Pedalea.WebApp.Models;
using System.Text.Json;
using static Pedalea.WebApp.Helpers.ModalHelper;

namespace Pedalea.WebApp.Controllers
{
    public class PedidosController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly JsonSerializerOptions options = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
        public PedidosController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Pedido> pedidos = new List<Pedido>();
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiPedidos");
                HttpResponseMessage response = await client.GetAsync("api/pedidos/GetPedidos");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    if (content != null)
                    {
                        pedidos = JsonSerializer.Deserialize<IEnumerable<Pedido>>(content, options);
                    }
                    return View(pedidos);
                }
                return View();
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        public IActionResult Create()
        {
            Pedido pedido = new();
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    HttpClient client = _httpClientFactory.CreateClient("PedaleaApiPedidos");
                    HttpResponseMessage response = await client.PostAsJsonAsync("api/pedidos/AddPedido", pedido);
                    if (response.IsSuccessStatusCode)
                    {
                        string content = await response.Content.ReadAsStringAsync();
                        if (content != null)
                        {
                            Pedido result = JsonSerializer.Deserialize<Pedido>(content, options);
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    return NotFound();
                }
                catch (Exception)
                {
                    return NotFound();
                }
            }
            return View(pedido);
        }


        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiPedidos");
                HttpResponseMessage response = await client.DeleteAsync($"api/pedidos/DeletePedido/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Pedido pedido = new();
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiPedidos");
                HttpResponseMessage response = await client.GetAsync($"api/pedidos/GetPedido/{id}");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    if (content != null)
                    {
                        pedido = JsonSerializer.Deserialize<Pedido>(content, options);
                    }
                    return View(pedido);
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NotFound();
        }
    }
}

Frontend/Pedalea.WebApp/Pedalea.WebApp/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using Pedalea.WebApp.Models;
using System.Text.Json;
using static Pedalea.WebApp.Helpers.ModalHelper;

namespace Pedalea.WebApp.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly JsonSerializerOptions options = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };
        public ProductosController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Producto> productos = new List<Producto>();
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                HttpResponseMessage response = await client.GetAsync("api/productos/GetProducts");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    if (content != null)
                    {
                        productos = JsonSerializer.Deserialize<IEnumerable<Producto>>(content, options);
                    }
                    return View(productos);
                }
                return View();
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        public IActionResult Create()
        {
            Producto producto = new();
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Producto producto)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                    HttpResponseMessage response = await client.PostAsJsonAsync("api/productos/AddProduct", producto);
                    if (response.IsSuccessStatusCode)
                    {
                        string content = await response.Content.ReadAsStringAsync();
                        if (content != null)
                        {
                            Producto result = JsonSerializer.Deserialize<Producto>(content, options);
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    return NotFound();
                }
                catch (Exception)
                {
                    return NotFound();
                }
            }
            return View(producto);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Producto producto = new();
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                HttpResponseMessage response = await client.GetAsync($"api/productos/GetProduct/{id}");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    if (content != null)
                    {
                        producto = JsonSerializer.Deserialize<Producto>(content, options);
                    }
                    return View(producto);
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Producto model)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    Producto producto = new();
                    HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                    HttpResponseMessage response = await client.PutAsJsonAsync($"api/productos/UpdateProduct/{id}", model);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    return NotFound();
                }
                catch (Exception)
                {
                    return NotFound();
                }
            }
            return View(model);
        }

        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                HttpResponseMessage response = await client.DeleteAsync($"api/productos/DeleteProduct/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Producto producto = new();
            try
            {
                HttpClient client = _httpClientFactory.CreateClient("PedaleaApiProductos");
                HttpResponseMessage response = await client.GetAsync($"api/productos/GetProduct/{id}");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    if (content != null)
                    {
                        producto = JsonSerializer.Deserialize<Producto>(content, options);
                    }
                    return View(producto);
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NotFound();
        }
    }
}

Frontend/Pedalea.WebApp/Pedalea.WebApp/Views/Shared/_DeleteDialog.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

Frontend/Pedalea.WebApp/Pedalea.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pedalea.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pedalea.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pedalea.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pedalea.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>